apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  argocd/app-name: rag-onesixtest-may29
  janus-idp.io/tekton: rag-onesixtest-may29
  backstage.io/kubernetes-id: rag-onesixtest-may29
  backstage.io/kubernetes-namespace: rhdh-app
  app.kubernetes.io/part-of: rag-onesixtest-may29
resources:
  - initialize-namespace/
  - deployment-model-server.yaml
  - service-model-server.yaml
  - deployment.yaml
  - route.yaml
  - service.yaml
  - model-config.yaml
  - deployment-database.yaml
  - service-database.yaml
  - database-config.yaml
